#!/bin/sh
# Start/stop the UbiCD dynamic.

### BEGIN INIT INFO
# Provides:          ubicd_dynamic
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      $network
# Should-Stop:       $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: UbiCD dynamic
# Description:       web server for the dynamic part of Ubiquitous Citizen Desk
### END INIT INFO

. /lib/lsb/init-functions

DAEMON=/opt/ubicd/sbin/ubicd_dynamic.py
PIDFILE=/opt/ubicd/var/run/ubicd_dynamic.pid

test -x $DAEMON || exit 0

case "$1" in
  start)
    log_daemon_msg "Starting UbiCD dynamic"
    log_progress_msg "ubicd_dynamic"

    start-stop-daemon --start --quiet --pidfile $PIDFILE --startas $DAEMON || true

    log_end_msg 0
    ;;

  stop)
    log_daemon_msg "Stopping UbiCD dynamic"
    log_progress_msg "ubicd_dynamic"
    start-stop-daemon --stop --quiet \
        --pidfile $PIDFILE || true

    log_end_msg 0
    ;;

  reload)
    # We don't have support for this yet.
    exit 1
    ;;

  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|force-reload}"
    exit 1

esac

exit 0
